PACKAGE_NAME="hid-razer-barracuda"
PACKAGE_VERSION="0.3.2"
BUILT_MODULE_NAME[0]="hid-razer-barracuda"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
